module.exports = {
  'array-bracket-newline': ['error', 'consistent'],
  'array-bracket-spacing': ['error', 'never'],
  'array-element-newline': ['error', 'consistent'],
  'block-spacing': ['error', 'always'],
  'brace-style': ['error', '1tbs'],
  'camelcase': 'error',
  'capitalized-comments': ['error', 'always', {
    ignoreConsecutiveComments: true,
  }],
  'comma-dangle': ['error', 'always-multiline'],
  'comma-spacing': 'error',
  'comma-style': 'error',
  'computed-property-spacing': 'error',
  'consistent-this': ['error', 'that'],
  'eol-last': ['error', 'always'],
  'func-call-spacing': ['error', 'never'],
  'func-name-matching': 'off',
  'func-names': ['error', 'always'],
  'func-style': ['error', 'expression'],
  'function-call-argument-newline': ['error', 'consistent'],
  'function-paren-newline': ['error', 'consistent'],
  'id-blacklist': ['error', 'data', 'err', 'e', 'cb', 'callback'],
  'id-length': ['error', {
    min: 2,
    max: 32,
  }],
  'id-match': 'off',
  'implicit-arrow-linebreak': ['error', 'beside'],
  'indent': ['error', 2],
  'jsx-quotes': 'off',
  'key-spacing': ['error', {
    beforeColon: false,
    afterColon: true,
    mode: 'strict',
  }],
  'keyword-spacing': ['error', {
    before: true,
    after: true,
  }],
  'line-comment-position': ['error', 'above'],
  'linebreak-style': 'off',
  'lines-around-comment': ['error', {
    beforeBlockComment: true,
    afterBlockComment: false,
    beforeLineComment: true,
    afterLineComment: false,
    allowBlockStart: true,
    allowBlockEnd: false,
    allowClassStart: true,
    allowClassEnd: false,
    allowObjectStart: true,
    allowObjectEnd: false,
    allowArrayStart: true,
    allowArrayEnd: false,
  }],
  'lines-between-class-members': ['error', 'always', {
    exceptAfterSingleLine: true,
  }],
  'max-depth': ['error', 4],
  'max-len': ['error', {
    code: 80,
    ignoreUrls: true,
    ignoreStrings: true,
  }],
  'max-lines': 'off',
  'max-lines-per-function': 'off',
  'max-nested-callbacks': ['error', 5],
  'max-params': ['error', 5],
  'max-statements': ['error', 10],
  'max-statements-per-line': ['error', {
    max: 1,
  }],
  'multiline-comment-style': ['error', 'separate-lines'],
  'multiline-ternary': ['error', 'always'],
  'new-cap': 'error',
  'new-parens': 'error',
  'newline-per-chained-call': ['error', {
    ignoreChainWithDepth: 2,
  }],
  'no-array-constructor': 'error',
  'no-bitwise': 'error',
  'no-continue': 'error',
  'no-inline-comments': 'error',
  'no-lonely-if': 'error',
  'no-mixed-operators': 'error',
  'no-mixed-spaces-and-tabs': 'error',
  'no-multi-assign': 'error',
  'no-multiple-empty-lines': 'error',
  'no-negated-condition': 'error',
  'no-nested-ternary': 'error',
  'no-new-object': 'error',
  'no-plusplus': 'error',
  'no-tabs': 'error',
  'no-ternary': 'off',
  'no-trailing-spaces': ['error', {
    skipBlankLines: true,
    ignoreComments: true,
  }],
  'no-underscore-dangle': 'error',
  'no-unneeded-ternary': 'error',
  'no-whitespace-before-property': 'error',

  // We disallow non-block statements altogether with the `curly` rule.
  'nonblock-statement-body-position': 'off',
  'object-curly-newline': ['error', {
    consistent: true,
  }],
  'object-curly-spacing': ['error', 'always'],
  'object-property-newline': ['error', {
    allowAllPropertiesOnSameLine: true,
  }],
  'one-var': ['error', 'never'],
  'one-var-declaration-per-line': 'off',
  'operator-assignment': ['error', 'never'],
  'operator-linebreak': ['error', 'before'],
  'padded-blocks': ['error', 'never'],
  'padding-line-between-statements': 'off',
  'prefer-exponentiation-operator': 'error',
  'prefer-object-spread': 'error',
  'quote-props': ['error', 'consistent'],
  'quotes': ['error', 'single'],
  'semi': ['error', 'never'],
  'semi-spacing': 'off',
  'semi-style': 'off',
  'sort-keys': 'off',
  'sort-vars': 'off',
  'space-before-blocks': ['error', 'always'],
  'space-before-function-paren': ['error', 'always'],
  'space-in-parens': ['error', 'never'],
  'space-infix-ops': 'error',
  'space-unary-ops': 'error',
  'spaced-comment': ['error', 'always'],
  'switch-colon-spacing': ['error', {
    after: true,
    before: false,
  }],
  'template-tag-spacing': ['error', 'always'],
  'unicode-bom': 'off',
  'wrap-regex': 'error',

  // ES6

  'arrow-body-style': ['error', 'as-needed'],
  'arrow-parens': ['error', 'always'],
  'arrow-spacing': ['error', {
    before: true,
    after: true,
  }],
  'constructor-super': 'error',
  'no-class-assign': 'error',
  'no-confusing-arrow': 'off',
  'no-const-assign': 'error',
  'no-dupe-class-members': 'error',
  'no-duplicate-imports': 'error',
  'no-this-before-super': 'error',
  'no-useless-computed-key': 'error',

  // This is disabled in favour of @typescript-eslint/no-useless-constructor
  'no-useless-constructor': 'off',

  'no-useless-rename': 'error',
  'no-var': 'error',
  'object-shorthand': ['error', 'always'],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-destructuring': 'error',
  'prefer-numeric-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'rest-spread-spacing': ['error', 'never'],
  'sort-imports': 'off',
  'template-curly-spacing': ['error', 'never'],

  // Basics

  'for-direction': 'error',
  'getter-return': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': ['error', 'except-parens'],
  'no-constant-condition': 'error',
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-dupe-args': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-ex-assign': 'error',
  'no-extra-parens': ['error', 'all'],
  'no-extra-semi': 'error',
  'no-func-assign': 'error',
  'no-import-assign': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-misleading-character-class': 'error',
  'no-obj-calls': 'error',
  'no-prototype-builtins': 'error',
  'no-regex-spaces': 'error',
  'no-setter-return': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-unexpected-multiline': 'error',
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'require-atomic-updates': 'error',
  'use-isnan': 'error',
  'valid-typeof': 'error',

  // Best Practices

  'accessor-pairs': ['error', {
    setWithoutGet: true,
    getWithoutSet: false,

    // EnforceForClassMembers: true,
  }],
  'array-callback-return': 'error',
  'block-scoped-var': 'error',
  'class-methods-use-this': 'off',
  'complexity': ['error', 10],
  'consistent-return': ['error', {
    treatUndefinedAsUnspecified: true,
  }],
  'curly': ['error', 'all'],
  'default-case': 'error',

  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-location': ['error', 'property'],
  'dot-notation': ['error', {
    allowKeywords: true,
    allowPattern: '^[a-z]+(_[a-z]+)+$',
  }],
  'eqeqeq': ['error', 'always'],
  'grouped-accessor-pairs': 'error',
  'guard-for-in': 'error',
  'max-classes-per-file': ['error', 1],
  'no-alert': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-constructor-return': 'error',
  'no-div-regex': 'error',
  'no-else-return': 'error',
  'no-empty-function': 'error',
  'no-empty-pattern': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-fallthrough': 'error',
  'no-floating-decimal': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': 'off',
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-invalid-this': 'error',
  'no-iterator': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-loop-func': 'error',
  'no-magic-numbers': 'off',
  'no-multi-spaces': 'error',
  'no-multi-str': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'error',
  'no-proto': 'error',
  'no-redeclare': 'error',
  'no-restricted-properties': 'error',
  'no-return-assign': 'error',
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-throw-literal': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unused-expressions': ['error', {
    allowShortCircuit: true,
    allowTernary: true,
  }],
  'no-unused-labels': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-concat': 'error',
  'no-useless-escape': 'error',
  'no-useless-return': 'error',
  'no-void': 'error',
  'no-warning-comments': 'error',
  'no-with': 'error',
  'prefer-named-capture-group': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': 'error',
  'radix': 'error',
  'require-await': 'error',
  'require-unicode-regexp': 'error',
  'vars-on-top': 'error',
  'wrap-iife': 'error',
  'yoda': ['error', 'never'],
}
